import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideNavigation from './component/navigation/sideNav'
import TopNavigation from './component/navigation/TopNavigation'
import MainCard from './component/game-card/MainCard'
import Footer from './component/footer'
import { allData } from './component/game-card/utils/allData'
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gamemano',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader
          color="#DAB785"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        <SideNavigation />
        <TopNavigation />
        
        {children}
        <MainCard {...allData['2']} />
        <div className='gapDiv'></div>
        <MainCard {...allData['3']} />
        <div className='gapDiv'></div>
        <MainCard {...allData['4']} />
        <div className='gapDiv'></div>
        <Footer />
      </body>
    </html>
  )
}
